'''
Golden tests for the sequence document.

For each payload in tests/static/golden (generated by the client test
client/tests/sequence/golden-payload.test.ts), generates the document and
compares its text to the expected text stored next to the payload.

- `UPDATE_GOLDEN=1 python3 -m pytest tests/test_golden.py` rewrites the expected text.
- Otherwise, the text is compared to the stored one.
A change of the payload format must not change the expected text.
'''
import os
from pathlib import Path
import json
import pytest
from docx.table import Table
from docx.text.paragraph import Paragraph
from generate_doc import generate_doc, DEFAULT_DOC_VERSION

GOLDEN_DIR = Path(__file__).parent / 'static' / 'golden'
PAYLOAD_SUFFIX = '.payload.json'
EXPECTED_SUFFIX = '.expected.txt'
UPDATE = os.environ.get('UPDATE_GOLDEN') == '1'

CASES = sorted(p.name[:-len(PAYLOAD_SUFFIX)] for p in GOLDEN_DIR.glob(f'*{PAYLOAD_SUFFIX}'))


def document_text(doc) -> str:
    ''' Text of the document body in reading order: one line per non-empty
        paragraph (prefixed with its style) and one line per table row
    '''
    lines = []
    for element in doc.element.body.iterchildren():
        tag = element.tag.split('}')[-1]
        if tag == 'p':
            paragraph = Paragraph(element, doc)
            text = ' '.join(paragraph.text.split())
            if text:
                lines.append(f'[{paragraph.style.name}] {text}')
        elif tag == 'tbl':
            for row in Table(element, doc).rows:
                cells = [' '.join(cell.text.split()) for cell in row.cells]
                lines.append('| ' + ' | '.join(cells) + ' |')
    return '\n'.join(lines) + '\n'


def test_cases_have_expected_text():
    expected = sorted(p.name[:-len(EXPECTED_SUFFIX)] for p in GOLDEN_DIR.glob(f'*{EXPECTED_SUFFIX}'))
    if UPDATE:
        for case in set(expected) - set(CASES):
            (GOLDEN_DIR / f'{case}{EXPECTED_SUFFIX}').unlink()
        return
    assert CASES
    assert expected == CASES


@pytest.mark.parametrize('case', CASES)
def test_golden_document(case):
    with open(GOLDEN_DIR / f'{case}{PAYLOAD_SUFFIX}') as f:
        payload = json.load(f)
    text = document_text(generate_doc(payload, DEFAULT_DOC_VERSION))
    expected_path = GOLDEN_DIR / f'{case}{EXPECTED_SUFFIX}'
    if UPDATE:
        expected_path.write_text(text)
        return
    assert text == expected_path.read_text()
