/**
 * Quoted identifiers (MLS 3.7 §2.3.1, docs/selection-keys.md)
 */
import { TemplateInterface, OptionInterface } from "../../src/data/template";
import {
  ConfigContext,
  constructSelectionPath,
} from "../../src/interpreter/interpreter";
import {
  mapToDisplayOptions,
  FlatConfigOption,
} from "../../src/interpreter/display-option";
import { ConfigValues } from "../../src/utils/modifier-helpers";

/**
 * Options generated from server/tests/static-data/QuotedPackage via server parser.
 * This file is generated by running:
 *   cd server && npx jest tests/integration/parser/quoted-identifiers.test.ts
 */
const {
  template,
  options,
}: {
  template: TemplateInterface;
  options: { [key: string]: OptionInterface };
} = require("../data/options-QuotedTemplate.json");

const T = template.modelicaPath;
const C = "QuotedPackage.Component";
const VALVE = "QuotedPackage.Types.Valve";

const createContext = (selections: ConfigValues = {}) =>
  new ConfigContext(template, { selections } as any, options, selections);

const flatten = (items: any[], out: FlatConfigOption[] = []) => {
  items.forEach((i) =>
    "groupName" in i ? flatten(i.items, out) : out.push(i),
  );
  return out;
};

describe("Quoted identifiers", () => {
  it("resolves values through quoted names", () => {
    const context = createContext();
    expect(context.getValue("'c-d'.'a.b'")).toBe(false);
    expect(context.getValue("'c-d'.'val-1'")).toEqual(`${VALVE}.'three.way'`);
    expect(context.getValue("'rep.1'.'val-1'")).toEqual(`${VALVE}.'two-way'`);
    expect(context.getValue("'with-dash'")).toBe(true);
    // 'why\?' is bound to 'c-d'.'a.b', and unquoted to 'why\?'
    expect(context.getValue("'why\\?'")).toBe(false);
    expect(context.getValue("unquoted")).toBe(false);
    expect(context.getValue("valve")).toEqual(`${VALVE}.'13\\'H'`);
  });

  it("evaluates enable expressions with quoted names", () => {
    const context = createContext();
    expect(context.getOptionInstance("'rep.1'.'k\\?'")?.display).toBe(true);
    expect(context.getOptionInstance("'c-d'.'k\\?'")?.display).toBe(false);
    expect(context.getOptionInstance("'why\\?'")?.display).toBe(true);
    expect(context.getOptionInstance("unquoted")?.display).toBe(false);
  });

  it("applies selections keyed with quoted names", () => {
    const rep = `${T}.'rep.1'`;
    const context = createContext({
      [constructSelectionPath(rep, "'rep.1'")]: `${C}.Second`,
      [constructSelectionPath(`${C}.Partial.'a.b'`, "'rep.1'.'a.b'")]: false,
    });
    expect(context.getValue("'rep.1'")).toEqual(`${C}.Second`);
    // Modifier of the extends clause of Second
    expect(context.getValue("'rep.1'.'val-1'")).toEqual(`${VALVE}.'13\\'H'`);
    expect(context.getValue("'rep.1'.'only-second'")).toBe(false);
    expect(context.getOptionInstance("'rep.1'.'k\\?'")?.display).toBe(false);
  });

  it("displays the same options as with unquoted names", () => {
    // Quoted identifiers and their unquoted replacement, as in the JSON text
    const unquoted: [string, string][] = [
      ["'rep.1'", "rep1"],
      ["'c-d'", "cd"],
      ["'a.b'", "ab"],
      ["'val-1'", "val1"],
      ["'k\\\\?'", "k"],
      ["'with-dash'", "withDash"],
      ["'why\\\\?'", "why"],
      ["'only-second'", "onlySecond"],
      ["'two-way'", "twoWay"],
      ["'three.way'", "threeWay"],
      ["'13\\\\'H'", "H13"],
    ];
    const rename = (text: string) =>
      unquoted.reduce((t, [q, u]) => t.split(q).join(u), text);
    const renamed = JSON.parse(rename(JSON.stringify(options)));
    const displayed = (opts: { [key: string]: OptionInterface }) =>
      flatten(
        mapToDisplayOptions(
          new ConfigContext(template, { selections: {} } as any, opts, {}),
        ),
      ).map((o) => [o.scope, o.value]);

    const quotedDisplay = displayed(options);
    expect(quotedDisplay.map(([scope]) => scope)).toContain("'rep.1'.'a.b'");
    expect(JSON.parse(rename(JSON.stringify(quotedDisplay)))).toEqual(
      displayed(renamed),
    );
    expect(JSON.stringify(renamed)).not.toContain("'");
  });
});
