import { TemplateInterface, OptionInterface } from "../../src/data/template";
import { ConfigContext } from "../../src/interpreter/interpreter";

/**
 * Options generated from server/tests/static-data/TestPackage via server parser.
 * This file is generated by running:
 *   cd server && npx jest tests/integration/parser/modifiers.test.ts
 */
const testTemplateOptions: {
  [key: string]: OptionInterface;
} = require("../data/options-TestTemplate.json");

const templatePath = "TestPackage.Template.TestTemplate";

const template: TemplateInterface = {
  modelicaPath: templatePath,
  name: "Test Template",
  systemTypes: [],
  pathModifiers: {},
};

const mockConfig = {
  id: "test-config",
  name: "Test Config",
  templatePath,
  selections: {},
};

describe("Dialog(enable=false) disables the whole subtree (#599)", () => {
  let context: ConfigContext;

  beforeAll(() => {
    context = new ConfigContext(
      template,
      mockConfig as any,
      testTemplateOptions,
      {},
    );
  });

  it("keeps the disabled component's child options reachable for evaluation", () => {
    const option = testTemplateOptions[`${templatePath}.disabled_component`];
    expect(option.enable).toBe(false);
    expect(option.options).toContain(
      "TestPackage.Component.FirstComponent.component_param",
    );
  });

  it("hides parameters under a disabled component", () => {
    const instance = context.getOptionInstance(
      "disabled_component.component_param",
    );
    expect(instance).toBeDefined();
    expect(instance?.display).toBe(false);
  });

  it("still displays the same parameter under an enabled instance path", () => {
    const instance = context.getOptionInstance("first.component_param");
    expect(instance?.display).toBe(true);
  });

  it("does not treat a plain composite group as disabled", () => {
    // `third` has no Dialog annotation: enable is undefined, not false
    const option = testTemplateOptions[`${templatePath}.third`];
    expect(option.enable).toBeUndefined();
    expect(context._isInstanceDisabled("third")).toBe(false);

    const instance = context.getOptionInstance("third.component_param");
    expect(instance?.display).toBe(true);
  });
});
